stylesheets:
  admin:
    - 'public/stylesheets/admin/admin.css'
  admin_ie:
    - 'public/stylesheets/admin/admin-ie.css'

javascripts:
  admin:
    - 'public/javascripts/lib/modernizr.js'
    - 'public/javascripts/lib/selectivzr.js'
    - 'public/javascripts/lib/jquery.js'
    - 'public/javascripts/lib/jquery-ui.js'
    - 'public/javascripts/lib/jquery_ujs.js'
    - 'public/javascripts/lib/plugins/jquery.equalHeight.js'
    - 'public/javascripts/ckeditor/ckeditor.js'
    - 'public/javascripts/admin.js'

